import convertStockToDelta

convertStockToDelta.convertStockToDelta('AAPL')
convertStockToDelta.convertStockToDelta('ADBE')
convertStockToDelta.convertStockToDelta('AMD')
convertStockToDelta.convertStockToDelta('AMZN')
# convertStockToDelta.convertStockToDelta('ASUUY')
convertStockToDelta.convertStockToDelta('CMCSA')
convertStockToDelta.convertStockToDelta('CSCO')
convertStockToDelta.convertStockToDelta('GOOGL')
convertStockToDelta.convertStockToDelta('HP')
convertStockToDelta.convertStockToDelta('IBM')
convertStockToDelta.convertStockToDelta('INTC')
convertStockToDelta.convertStockToDelta('MSFT')
convertStockToDelta.convertStockToDelta('NTGR')
convertStockToDelta.convertStockToDelta('NVDA')
convertStockToDelta.convertStockToDelta('ORCL')
convertStockToDelta.convertStockToDelta('S')
convertStockToDelta.convertStockToDelta('T')
convertStockToDelta.convertStockToDelta('VZ')
